-- 通用配置表：只保留这一张表。
-- 每行代表一个模块配置项；后台按 模块名称 分组管理。
-- 服务器启动和 .reload config 时读取 启用状态=1 且 配置值非NULL 的 配置键/配置值。

DROP TABLE IF EXISTS `通用配置`; -- 旧表名，升级清理
DROP TABLE IF EXISTS `_通用配置`;

CREATE TABLE `_通用配置` (
  `配置ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '配置项ID',
  `模块ID` INT UNSIGNED NOT NULL COMMENT '模块编号，同一模块的配置使用相同模块ID',
  `模块名称` VARCHAR(100) NOT NULL COMMENT '中文模块名称',
  `模块标识` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '模块内部标识或来源',
  `配置键` VARCHAR(191) NOT NULL COMMENT '程序读取用的原始配置键，必须与 sConfigMgr->GetOption 名称一致',
  `配置名称` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '中文显示名称，方便后台管理',
  `配置值` TEXT NULL COMMENT '配置值；NULL表示不覆盖代码默认值，空字符串是有效配置值',
  `配置说明` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '中文配置说明',
  `启用状态` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '1=加载此配置，0=忽略此配置',
  PRIMARY KEY (`配置ID`),
  UNIQUE KEY `idx_配置键` (`配置键`),
  KEY `idx_模块ID` (`模块ID`),
  KEY `idx_模块名称` (`模块名称`),
  KEY `idx_启用状态` (`启用状态`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='通用配置 - 单表配置源';

INSERT INTO `_通用配置` (`模块ID`, `模块名称`, `模块标识`, `配置键`, `配置名称`, `配置值`, `配置说明`, `启用状态`) VALUES
(1, '属性调整光环', 'AuraAttributes', 'AuraAttributes.Enable', '是否启用', '1', '设置为 0 禁用', 1),
(1, '属性调整光环', 'AuraAttributes', 'AuraAttributes.DebugMode', '调试模式', '0', '设置为 1 启用', 1),
(1, '属性调整光环', 'AuraAttributes', 'AuraAttributes.LoadDelay', '加载延迟', '1', '服务器启动后多少秒加载模块', 1),
(2, '自动组队', 'AutoGroup', 'AutoGroup.DebugLevel', 'DebugLevel', '1', '默认: 1', 1),
(2, '自动组队', 'AutoGroup', 'AutoGroup.ZoneIdIsBlacklist', 'ZoneIdIsBlacklist', '0', '默认: 0', 1),
(2, '自动组队', 'AutoGroup', 'AutoGroup.DisableChatCommands', 'DisableChatCommands', '0', '默认: 0', 1),
(3, '自动拾取', 'AutoLoot', 'AutoLoot.Enable', '是否启用', '1', '设置为0禁用', 1),
(3, '自动拾取', 'AutoLoot', 'AutoLoot.Money', '拾取金币', '1', '设置为0禁用', 1),
(3, '自动拾取', 'AutoLoot', 'AutoLoot.QuestItems', '拾取任务物品', '1', '设置为0禁用', 1),
(3, '自动拾取', 'AutoLoot', 'AutoLoot.Debug', '是否调试', '0', '设置为1启用', 1),
(4, '境界系统', 'boundary', 'Boundary.Enable', '是否启用', '1', '是否启用境界系统', 1),
(4, '境界系统', 'boundary', 'Boundary.ExpRate', '经验倍率', '100', '境界升级经验获取比例(万分比,默认100=1%)', 1),
(4, '境界系统', 'boundary', 'Boundary.LevelLimit', '是否启用境界等级限制', '1', '是否启用境界等级限制', 1),
(4, '境界系统', 'boundary', 'Boundary.MinLevel', '最低等级', '1', '开启境界系统最低等级要求', 1),
(4, '境界系统', 'boundary', 'Boundary.AutoInit', '自动初始化', '1', '是否在角色创建时自动初始化境界数据', 1),
(4, '境界系统', 'boundary', 'Boundary.ShowExpMessage', '是否显示经验获取消息', '0', '是否显示经验获取消息', 1),
(5, '突破系统', 'breakthrough_system', 'BreakthroughSystem.Enable', '是否启用', '1', '0 - 禁用', 1),
(5, '突破系统', 'breakthrough_system', 'BreakthroughSystem.Announce', '发送公告', '1', '0 - 禁用', 1),
(5, '突破系统', 'breakthrough_system', 'BreakthroughSystem.MaxLevel', '最高等级', '10000', '默认: 100', 1),
(5, '突破系统', 'breakthrough_system', 'BreakthroughSystem.DefaultLevel', '默认等级', '1', '默认: 1', 1),
(5, '突破系统', 'breakthrough_system', 'BreakthroughSystem.AutoApply', '自动应用', '1', '0 - 禁用', 1),
(5, '突破系统', 'breakthrough_system', 'Breakthrough.DebugSkillDetail', 'DebugSkillDetail', '0', '1 - 启用', 1),
(6, '货币系统', 'currency-system', 'CurrencySystem.Enable', '是否启用', '1', '设置为 0 禁用', 1),
(6, '货币系统', 'currency-system', 'CurrencySystem.StartingCurrencies', '默认所有货币初始值为0，防止玩家通过创建新角色刷取货币', '泡点:0,积分:0,妖币:0,魔币:0,仙币:0,神币:0', '默认所有货币初始值为0，防止玩家通过创建新角色刷取货币', 1),
(6, '货币系统', 'currency-system', 'CurrencySystem.CommandPermissionLevel', 'CommandPermissionLevel', '1', '2 - 高级管理员', 1),
(6, '货币系统', 'currency-system', 'CurrencySystem.AutoSaveInterval', 'AutoSaveInterval', '1', '默认: 1 (1分钟)', 1),
(7, '自定义阵营', 'CustomFaction', 'CustomFaction.Enable', '是否启用', '1', '0 - 禁用', 1),
(9, '事件触发', 'event_trigger', 'EventTrigger.Enable', '是否启用', '1', '默认: 1（开启）', 1),
(9, '事件触发', 'event_trigger', 'EventTrigger.UpdateInterval', '更新间隔', '5000', '默认: 5000 (5秒)', 1),
(10, '硬核模式', 'HardcoreMode', 'HardcoreMode.Enable', '是否启用', '1', '0 - 禁用', 1),
(10, '硬核模式', 'HardcoreMode', 'HardcoreMode.AnnounceLogin', 'AnnounceLogin', '1', '0 - 禁用', 1),
(10, '硬核模式', 'HardcoreMode', 'HardcoreMode.AnnounceLevelUp', 'AnnounceLevelUp', '1', '0 - 禁用', 1),
(10, '硬核模式', 'HardcoreMode', 'HardcoreMode.AnnounceDeath', 'AnnounceDeath', '1', '0 - 禁用', 1),
(10, '硬核模式', 'HardcoreMode', 'HardcoreMode.DefaultMode', 'DefaultMode', '0', '1 - 启用', 1),
(10, '硬核模式', 'HardcoreMode', 'HardcoreMode.EnableDebug', '启用调试', '0', '1 - 启用', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.Enable', '是否启用', '1', '0 (禁用)', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxLevel', '最高等级', '5000', '默认值: 2000', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.Debug', '是否调试', '1', '1 (启用)', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxHealth', '说明: 大于0时作为自定义上限；0表示仅受服务端字段可承载范围保护', '0', '说明: 大于0时作为自定义上限；0表示仅受服务端字段可承载范围保护', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxDamage', '说明: 大于0时作为自定义上限', '0.0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxArmor', '说明: 大于0时作为自定义上限', '0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxAttackPower', '说明: 大于0时作为自定义上限', '0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxResistance', '说明: 大于0时作为自定义上限', '0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxMana', '说明: 大于0时作为自定义上限', '0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxSpellPower', '说明: 大于0时作为自定义上限', '0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxCritChance', '说明: 当生物暴击几率超过此值时，会被自动限制在此范围内', '95.0', '说明: 当生物暴击几率超过此值时，会被自动限制在此范围内', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxHitChance', '说明: 当生物命中几率超过此值时，会被自动限制在此范围内', '100.0', '说明: 当生物命中几率超过此值时，会被自动限制在此范围内', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxHaste', '说明: 大于0时作为自定义上限', '0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxExpertise', '说明: 大于0时作为自定义上限', '0', '说明: 大于0时作为自定义上限', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxDodgeChance', '说明: 当生物闪避几率超过此值时，会被自动限制在此范围内', '95.0', '说明: 当生物闪避几率超过此值时，会被自动限制在此范围内', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxParryChance', '说明: 当生物招架几率超过此值时，会被自动限制在此范围内', '95.0', '说明: 当生物招架几率超过此值时，会被自动限制在此范围内', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxBlockChance', '说明: 当生物格挡几率超过此值时，会被自动限制在此范围内', '95.0', '说明: 当生物格挡几率超过此值时，会被自动限制在此范围内', 1),
(11, '幻境系统', 'HuanJingSystem', 'HuanJingSystem.MaxMovementSpeed', '说明: 当生物移动速度超过此值时，会被自动限制在此范围内', '100.0', '说明: 当生物移动速度超过此值时，会被自动限制在此范围内', 1),
(12, '物品租赁', 'item_lease', 'ItemLease.Enable', '是否启用', '1', '是否启用物品租赁系统', 1),
(12, '物品租赁', 'item_lease', 'ItemLease.CheckInterval', '检查间隔', '60', '检查物品过期的时间间隔（秒）', 1),
(12, '物品租赁', 'item_lease', 'ItemLease.NotifyBeforeExpire', '到期前通知', '300', '当物品即将过期时，提前这么多秒通知玩家', 1),
(13, '每日购买限制', 'item_purchase_limit', 'ItemPurchaseLimit.Enable', '是否启用', '1', '模块开关', 1),
(13, '每日购买限制', 'item_purchase_limit', 'ItemPurchaseLimit.Debug', '是否调试', '0', '调试模式开关（0=关闭, 1=开启）', 1),
(13, '每日购买限制', 'item_purchase_limit', 'ItemPurchaseLimit.NotifyPlayer', '通知玩家', '1', '通知玩家购买限制信息（0=关闭, 1=开启）', 1),
(14, '物品AI', 'item-with-ai', '物品带AI.启用', '是否启用', '1', '0 - 禁用', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.Enable', '是否启用', '1', '启用物品强化系统', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.FailureProtection', '强化失败保护（0=禁用，1=启用）', '1', '强化失败保护（0=禁用，1=启用）', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.ShowSuccessRate', '强化成功率显示（0=禁用，1=启用）', '1', '强化成功率显示（0=禁用，1=启用）', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.Announce', '发送公告', '1', '当玩家强化达到特定等级时，全服公告', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.AnnounceLevel', '当强化等级达到或超过此值时进行公告', '10', '当强化等级达到或超过此值时进行公告', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.GoldCostRate', '实际消耗 = 基础消耗 * 此系数', '1.0', '实际消耗 = 基础消耗 * 此系数', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.MaterialCostRate', '实际消耗 = 基础消耗 * 此系数', '1.0', '实际消耗 = 基础消耗 * 此系数', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.SuccessRateRate', '实际成功率 = 基础成功率 * 此系数', '1.0', '实际成功率 = 基础成功率 * 此系数', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.AttributeRate', '实际属性加成 = 基础属性加成 * 此系数', '1.0', '实际属性加成 = 基础属性加成 * 此系数', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.Cooldown', '两次强化之间的最小间隔时间', '0', '两次强化之间的最小间隔时间', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.MaxLevel', '最高等级', '20', '物品强化的最大等级上限', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.DebugMode', '调试模式', '0', '启用后会输出更多日志信息', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.RecordCacheTTL', '用于控制物品强化记录在内存中的缓存时间，0 表示禁用缓存或立即过期', '0', '用于控制物品强化记录在内存中的缓存时间，0 表示禁用缓存或立即过期', 1),
(15, '物品强化', 'ItemEnhancement', 'ItemEnhancement.LoginMessage', '启用后玩家登录时会显示物品强化系统的提示消息', '0', '启用后玩家登录时会显示物品强化系统的提示消息', 1),
(16, '物品成长', 'ItemGrowth', 'ItemGrowth.Enable', '是否启用', '1', '0 - 禁用', 1),
(16, '物品成长', 'ItemGrowth', 'ItemGrowth.AnnounceModule', 'AnnounceModule', '1', '0 - 禁用', 1),
(16, '物品成长', 'ItemGrowth', 'ItemGrowth.MaxLevel', '最高等级', '100', '默认: 100', 1),
(16, '物品成长', 'ItemGrowth', 'ItemGrowth.BaseExpMultiplier', 'BaseExpMultiplier', '1.0', '默认: 1.0', 1),
(16, '物品成长', 'ItemGrowth', 'ItemGrowth.UpgradeSuccessRate', 'UpgradeSuccessRate', '80', '默认: 80', 1),
(16, '物品成长', 'ItemGrowth', 'ItemGrowth.RequireSoulbound', 'RequireSoulbound', '1', '0 - 不要求', 1),
(16, '物品成长', 'ItemGrowth', 'ItemGrowth.AutoApplyAttributes', '注意: 即使设置为0，仍可通过命令手动应用属性组效果', '1', '注意: 即使设置为0，仍可通过命令手动应用属性组效果', 1),
(17, '物品鉴定', 'ItemIdentificationSystem', 'ItemIdentificationSystem.Enable', '是否启用', '1', '设置为0禁用', 1),
(17, '物品鉴定', 'ItemIdentificationSystem', 'ItemIdentificationSystem.BaseSuccessRate', '基础成功率', '100', '默认: 100 (100%)', 1),
(17, '物品鉴定', 'ItemIdentificationSystem', 'ItemIdentificationSystem.DestroyOnFail', '失败销毁', '0', '设置为1启用销毁', 1),
(17, '物品鉴定', 'ItemIdentificationSystem', 'ItemIdentificationSystem.Cost', '消耗', '10000', '默认: 10000 (1金币)', 1),
(17, '物品鉴定', 'ItemIdentificationSystem', 'ItemIdentificationSystem.EnableAnnounce', '启用公告', '1', '设置为0禁用', 1),
(17, '物品鉴定', 'ItemIdentificationSystem', 'ItemIdentificationSystem.Debug', '是否调试', '0', '设置为1启用', 1),
(18, '物品购买条件', 'ItemPurchaseCondition', 'ItemPurchaseCondition.Enable', '是否启用', '1', '0 - 禁用', 1),
(19, '物品回收', 'ItemRecycle', 'ItemRecycle.Enable', '是否启用', '1', '是否启用物品回收模块', 1),
(19, '物品回收', 'ItemRecycle', 'ItemRecycle.DebugMode', '调试模式', '0', '是否启用调试模式', 1),
(19, '物品回收', 'ItemRecycle', 'ItemRecycle.AutoCheckInterval', '自动检查间隔', '5000', '自动回收检查间隔（毫秒）', 1),
(19, '物品回收', 'ItemRecycle', 'ItemRecycle.DefaultInterval', '默认间隔', '60', '默认自动回收间隔（秒）', 1),
(19, '物品回收', 'ItemRecycle', 'ItemRecycle.AllowCustomSettings', '允许自定义设置', '1', '是否允许玩家自定义回收设置', 1),
(19, '物品回收', 'ItemRecycle', 'ItemRecycle.MinInterval', '最小间隔', '10', '最小回收间隔（秒）', 1),
(19, '物品回收', 'ItemRecycle', 'ItemRecycle.MaxInterval', '最大间隔', '3600', '最大回收间隔（秒）', 1),
(20, '物品出售奖励', 'ItemSellReward', 'ItemSellReward.Enable', '是否启用', '1', '0 - 禁用', 1),
(20, '物品出售奖励', 'ItemSellReward', 'ItemSellReward.DebugMode', '调试模式', '0', '1 - 启用', 1),
(20, '物品出售奖励', 'ItemSellReward', 'ItemSellReward.AllowGMCommands', '允许GM命令', '1', '0 - 禁止', 1),
(21, '物品合成', 'ItemSynthesis', 'ItemSynthesis.Enable', '是否启用', '1', '默认: 1 (启用)', 1),
(21, '物品合成', 'ItemSynthesis', 'ItemSynthesis.Announce', '发送公告', '1', '默认: 1 (启用)', 1),
(21, '物品合成', 'ItemSynthesis', 'ItemSynthesis.AnnounceOnlyRare', 'AnnounceOnlyRare', '1', '默认: 1 (启用)', 1),
(21, '物品合成', 'ItemSynthesis', 'ItemSynthesis.InitDelay', 'InitDelay', '30', '默认: 30', 1),
(21, '物品合成', 'ItemSynthesis', 'ItemSynthesis.DefaultAnnounceFormat', '$newitem - 新物品名称', '|cFFFF0000[物品合成]|r 恭喜玩家 |cFF00FFFF$player|r 成功将 |cFF00FF00$olditem|r 合成为 |cFFFF00FF$newitem|r！', '$newitem - 新物品名称', 1),
(22, '物品使用条件', 'ItemUseCondition', 'ItemUseCondition.Enable', '是否启用', '1', '是否启用物品使用条件系统', 1),
(23, '物品使用奖励', 'ItemUseReward', 'ItemUseReward.Enable', '是否启用', '1', '是否启用物品使用奖励模块', 1),
(23, '物品使用奖励', 'ItemUseReward', 'ItemUseReward.DebugMode', '调试模式', '0', '是否启用调试模式', 1),
(23, '物品使用奖励', 'ItemUseReward', 'ItemUseReward.AllowGMCommands', '允许GM命令', '1', '是否允许执行GM命令', 1),
(23, '物品使用奖励', 'ItemUseReward', 'ItemUseReward.ConsumeItemByDefault', '默认是否消耗物品（可以在数据库中为每个物品单独设置）', '1', '默认是否消耗物品（可以在数据库中为每个物品单独设置）', 1),
(24, '商城系统', 'mall_system', 'Mall.System.Enable', '是否启用', '1', '0 - 禁用', 1),
(24, '商城系统', 'mall_system', 'Mall.System.Announce', '发送公告', '1', '0 - 禁用', 1),
(24, '商城系统', 'mall_system', 'Mall.System.MaxItems', 'MaxItems', '8', '默认: 8', 1),
(24, '商城系统', 'mall_system', 'Mall.System.MaxCategories', 'MaxCategories', '12', '默认: 12', 1),
(24, '商城系统', 'mall_system', 'Mall.System.ShowStartupInfo', 'ShowStartupInfo', '1', '0 - 不显示', 1),
(25, '地图属性', 'map_attributes', 'MapAttributes.Enable', '是否启用', '1', '设置为0禁用', 1),
(25, '地图属性', 'map_attributes', 'MapAttributes.Debug', '是否调试', '0', '设置为1启用', 1),
(25, '地图属性', 'map_attributes', 'MapAttributes.Announce', '发送公告', '1', '设置为0禁用', 1),
(25, '地图属性', 'map_attributes', 'MapAttributes.UpdateInterval', '更新间隔', '5000', '默认: 5000 (5秒)', 1),
(26, '深渊修仙', 'mod_abyss_cultivation', 'AbyssCultivation.Enable', '是否启用', '1', '是否启用', 1),
(26, '深渊修仙', 'mod_abyss_cultivation', 'AbyssCultivation.Debug', '是否调试', '0', '是否调试', 1),
(26, '深渊修仙', 'mod_abyss_cultivation', 'AbyssCultivation.AutoBeginOnMapEnter', 'AutoBeginOnMapEnter', '0', 'AutoBeginOnMapEnter', 1),
(27, '公告模板', 'mod_announcement_template', 'AnnouncementTemplate.Enable', '是否启用', '1', '是否启用公告模板模块', 1),
(28, '飞升系统', 'mod_ascension_system', '飞升系统.启用', '是否启用', '1', '默认: 1 (启用)', 1),
(28, '飞升系统', 'mod_ascension_system', '飞升系统.调试模式', '调试模式', '0', '默认: 0 (禁用)', 1),
(28, '飞升系统', 'mod_ascension_system', '飞升系统.属性倍率', '属性倍率', '1.0', '默认: 1.0', 1),
(28, '飞升系统', 'mod_ascension_system', '飞升系统.需要等级', '需要等级', '1', '默认: 1', 1),
(28, '飞升系统', 'mod_ascension_system', '飞升系统.显示提示', '显示提示', '1', '默认: 1 (启用)', 1),
(28, '飞升系统', 'mod_ascension_system', '飞升系统.自动解锁', '自动解锁', '0', '默认: 0 (禁用，需要满足解锁条件)', 1),
(2, '自动组队', 'mod_auto_group', 'AutoGroup.Enable', '是否启用', '1', '1 - 启用', 1),
(2, '自动组队', 'mod_auto_group', 'AutoGroup.CheckInterval', '检查间隔', '5000', '默认: 5000 (5秒)', 1),
(29, '挑战幻境', 'mod_challenge_mirage', 'ChallengeMirage.Enable', '是否启用', '1', '默认: 1', 1),
(29, '挑战幻境', 'mod_challenge_mirage', 'ChallengeMirage.Debug', '是否调试', '0', '默认: 0', 1),
(29, '挑战幻境', 'mod_challenge_mirage', 'ChallengeMirage.DefaultLayer', 'DefaultLayer', '0', '默认: 0', 1),
(29, '挑战幻境', 'mod_challenge_mirage', 'ChallengeMirage.MaxLevel', '最高等级', '9999999', '默认: 9999999', 1),
(30, '称号系统', 'mod_chenghao_system', 'ChenghaoSystem.Enable', '是否启用', '1', '1 - 启用', 1),
(30, '称号系统', 'mod_chenghao_system', 'ChenghaoSystem.NotifyPlayer', '通知玩家', '1', '1 - 发送', 1),
(31, '职业属性', 'mod_class_attributes', 'ClassAttributes.Enable', '是否启用', '1', '0 - 禁用', 1),
(31, '职业属性', 'mod_class_attributes', 'ClassAttributes.Announce', '发送公告', '0', '1 - 启用', 1),
(31, '职业属性', 'mod_class_attributes', 'ClassAttributes.Debug', '是否调试', '0', '1 - 启用', 1),
(31, '职业属性', 'mod_class_attributes', 'ClassAttributes.AutoReload', 'AutoReload', '1', '0 - 禁用', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.Enable', '是否启用', '1', '是否启用生物属性调整模块', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.ShowLoadInfo', '显示加载信息', '1', '是否在服务器启动时显示模块加载信息', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.ShowKillInfo', '是否在生物死亡时显示击杀信息', '1', '是否在生物死亡时显示击杀信息', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.ShowSpawnInfo', '是否在生物生成时显示生成信息', '1', '是否在生物生成时显示生成信息', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.EnableModelChange', '是否启用生物模型修改', '1', '是否启用生物模型修改', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.EnableMovementChange', '是否启用生物移动修改', '1', '是否启用生物移动修改', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.EnableCombatAttributesChange', '是否启用生物战斗属性修改', '1', '是否启用生物战斗属性修改', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.EnableLootChange', '是否启用生物掉落修改', '1', '是否启用生物掉落修改', 1),
(32, '生物属性', 'mod_creature_attributes', 'CreatureAttributes.EnableDescription', '是否启用生物描述显示', '0', '是否启用生物描述显示', 1),
(33, '修仙系统', 'mod_cultivation_system', 'Cultivation.Enable', '是否启用', '1', '0  - (禁用)', 1),
(33, '修仙系统', 'mod_cultivation_system', 'Cultivation.Debug', '是否调试', '0', '1  - (启用)', 1),
(33, '修仙系统', 'mod_cultivation_system', 'Cultivation.TribulationCooldown', 'TribulationCooldown', '600', 'TribulationCooldown', 1),
(34, '切割系统', 'mod_cut_system', 'CutSystem.Enable', '是否启用', '1', '默认: 1', 1),
(34, '切割系统', 'mod_cut_system', 'CutSystem.Debug', '是否调试', '0', '默认: 0', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Eluna.Enabled', '是否启用', 'true', '是否启用', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Eluna.TraceBack', 'TraceBack', 'false', 'TraceBack', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Eluna.ScriptPath', 'ScriptPath', 'lua_scripts', 'ScriptPath', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Eluna.PlayerAnnounceReload', 'PlayerAnnounceReload', 'false', 'PlayerAnnounceReload', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Eluna.RequirePaths', 'RequirePaths', ';', 'Lua require 搜索路径；分号表示不追加额外路径', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Eluna.RequireCPaths', 'RequireCPaths', ';', 'Lua C require 搜索路径；分号表示不追加额外路径', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Appender.ElunaLog', 'ElunaLog', '2,5,0,eluna.log,w', 'ElunaLog', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Appender.ElunaConsole', 'ElunaConsole', '1,4,0,"0 9 0 3 5 0', 'ElunaConsole', 1),
(35, 'Eluna脚本', 'mod_eluna', 'Logger.eluna', 'eluna', '4,ElunaLog ElunaConsole', 'eluna', 1),
(36, '幻化系统', 'mod_fashion_system', 'FashionSystem.Enable', '是否启用', '1', '默认: 1', 1),
(36, '幻化系统', 'mod_fashion_system', 'FashionSystem.Debug', '是否调试', '0', '默认: 0', 1),
(37, '治疗符文', 'mod_heal_rune_system', 'HealRune.Enable', '是否启用', '1', '回血神符系统模块配置            #', 1),
(37, '治疗符文', 'mod_heal_rune_system', 'HealRune.NotifyPlayer', '通知玩家', '1', '通知玩家', 1),
(37, '治疗符文', 'mod_heal_rune_system', 'HealRune.TickIntervalMs', 'TickIntervalMs', '1000', 'TickIntervalMs', 1),
(37, '治疗符文', 'mod_heal_rune_system', 'HealRune.Debug', '是否调试', '0', '是否调试', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.Enable', '是否启用', '1', '0 - 禁用', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.Announce', '发送公告', '1', '0 - 禁用', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.LoginMessage', 'LoginMessage', '0', '1 - 启用', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.AutoGenerateOnLoot', 'AutoGenerateOnLoot', '0', '1 - 启用', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.AutoGenerateMethod', 'AutoGenerateMethod', '1', '3 - 随机生成', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.ShowInTooltip', 'ShowInTooltip', '1', '0 - 禁用', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.ApplyOnEquip', 'ApplyOnEquip', '1', '0 - 禁用', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.ForceRefreshOnLogin', 'ForceRefreshOnLogin', '0', '1 - 启用（强制刷新）', 1),
(38, '物品属性', 'mod_item_attributes', 'ItemAttributes.Debug.Performance', 'Performance', '0', '1 - 启用', 1),
(39, '背包属性加成', 'mod_item_backpack_bonus', 'ItemBackpackBonus.Enable', '是否启用', '1', '1 - 启用', 1),
(39, '背包属性加成', 'mod_item_backpack_bonus', 'ItemBackpackBonus.RefreshInterval', '如果担心某些自定义脚本绕过物品移动事件，可设置为 3000', '0', '如果担心某些自定义脚本绕过物品移动事件，可设置为 3000', 1),
(40, '物品套装', 'mod_item_sets', '物品套装.启用', '是否启用', '1', '设置为0禁用整个模块', 1),
(40, '物品套装', 'mod_item_sets', '物品套装.调试模式', '调试模式', '0', '设置为1启用调试日志', 1),
(40, '物品套装', 'mod_item_sets', '物品套装.允许部分加成', '允许部分加成', '1', '默认: 1 (启用)', 1),
(40, '物品套装', 'mod_item_sets', '物品套装.最大套装数', '最大套装数', '10', '默认: 10', 1),
(40, '物品套装', 'mod_item_sets', '物品套装.显示效果提示', '显示效果提示', '0', '默认: 0 (禁用) - 关闭套装效果激活、获得/失去光环等提示信息', 1),
(40, '物品套装', 'mod_item_sets', '物品套装.显示套装标记', '显示套装标记', '1', '默认: 1 (启用)', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.Enable', '是否启用', '1', '设置为 0 禁用', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.LogLevel', 'LogLevel', '2', '默认: 2', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.ChanceModifier', '设置为 0.5 表示所有几率减半', '1.0', '设置为 0.5 表示所有几率减半', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.CooldownModifier', '设置为 0.5 表示所有冷却时间减半', '1.0', '设置为 0.5 表示所有冷却时间减半', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.PPMModifier', '设置为 2.0 表示触发频率翻倍', '1.0', '设置为 2.0 表示触发频率翻倍', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.MaxTriggersPerDamage', '如果玩家装备了很多击中触发技能，每次攻击最多只触发这个数量', '5', '如果玩家装备了很多击中触发技能，每次攻击最多只触发这个数量', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.GlobalTriggerCooldown', '两次击中触发之间的最小间隔时间', '500', '两次击中触发之间的最小间隔时间', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.ChargesModifier', '设置为 2.0 表示使用次数翻倍', '1.0', '设置为 2.0 表示使用次数翻倍', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.EnableRandomGeneration', '设置为 0 禁用', '1', '设置为 0 禁用', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.AllowPlayerCommands', '设置为 0 禁用', '1', '设置为 0 禁用', 1),
(41, '物品技能', 'mod_item_skills', 'ItemSkills.MinGMRankForCommands', 'MinGMRankForCommands', '1', '默认: 1', 1),
(42, '魔次系统', 'mod_magic_hit_system', 'MagicHitSystem.Enable', '是否启用', '1', '0 (禁用)', 1),
(42, '魔次系统', 'mod_magic_hit_system', 'MagicHitSystem.MaxHitCount', '建议值: 根据服务器性能调整，建议不超过100000', '100000', '建议值: 根据服务器性能调整，建议不超过100000', 1),
(42, '魔次系统', 'mod_magic_hit_system', 'MagicHitSystem.DebugMode', '调试模式', '0', '日志通道: module.magichit', 1),
(42, '魔次系统', 'mod_magic_hit_system', 'MagicHitSystem.AnnounceToPlayer', '0 (不显示)', '0', '0 (不显示)', 1),
(42, '魔次系统', 'mod_magic_hit_system', 'MagicHitSystem.MaxCastEffectHits', '单次施法最大生效次数', '50', '单次施法效果的魔次命中上限，最小1', 1),
(43, '地图生物调整', 'mod_map_creature_adjust', 'MapCreatureAdjust.Enable', '是否启用', '1', '是否启用模块', 1),
(44, '材料仓库', 'mod_material_warehouse', 'MaterialWarehouse.Enable', '是否启用', '1', '是否启用材料仓库系统', 1),
(44, '材料仓库', 'mod_material_warehouse', 'MaterialWarehouse.DepositExistingOnAdd', '玩家把新物品加入仓库列表时，是否立刻把背包中已有的同类物品存入仓库', '1', '玩家把新物品加入仓库列表时，是否立刻把背包中已有的同类物品存入仓库', 1),
(44, '材料仓库', 'mod_material_warehouse', 'MaterialWarehouse.MaxWithdrawPerRequest', '单次从仓库取出的最大数量，防止误操作或异常请求', '100000', '单次从仓库取出的最大数量，防止误操作或异常请求', 1),
(45, '模型控制', 'mod_model_control', 'ModelControl.Enable', '是否启用', '1', '0 - 禁用', 1),
(45, '模型控制', 'mod_model_control', 'ModelControl.AnnounceEnable', 'AnnounceEnable', '0', '0 - 禁用', 1),
(45, '模型控制', 'mod_model_control', 'ModelControl.DefaultScale', 'DefaultScale', '1.0', '默认: 1.0', 1),
(45, '模型控制', 'mod_model_control', 'ModelControl.ApplyOnStartup', 'ApplyOnStartup', '1', '0 - 禁用', 1),
(46, '宠物属性调整', 'mod_pet_property_adjuster', 'PetPropertyAdjusterEnable', '设置为 0 关闭', '1', '设置为 0 关闭', 1),
(46, '宠物属性调整', 'mod_pet_property_adjuster', 'PetPropertyAdjusterTable', 'PetPropertyAdjusterTable', '_属性调整_宠物', '默认: _属性调整_宠物', 1),
(46, '宠物属性调整', 'mod_pet_property_adjuster', 'PetPropertyAdjusterShowLoadInfo', '设置为 0 关闭', '1', '设置为 0 关闭', 1),
(46, '宠物属性调整', 'mod_pet_property_adjuster', 'PetPropertyAdjusterUpdateInterval', 'PetPropertyAdjusterUpdateInterval', '2', '默认: 2', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.Enabled', '是否启用', '1', '可选值: 0 = 禁用, 1 = 启用', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.CommandLevel', '命令权限等级', '3', '4 = 控制台 (Console)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.LoadPlayerConfig', '加载玩家配置', '1', '默认值: 1 (启用)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.AutoSavePlayerConfig', '自动保存玩家配置', '1', '默认值: 1 (启用)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.AutoSaveInterval', '注意：仅当玩家在线且配置有更改时生效', '300', '注意：仅当玩家在线且配置有更改时生效', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.EnableLogging', '启用后，所有插件的创建、删除、启用、禁用操作都会被记录', '1', '启用后，所有插件的创建、删除、启用、禁用操作都会被记录', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.LogRetentionDays', '日志保留天数', '30', '超过指定天数的日志记录将被自动删除', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.ValidateOnStartup', 'ValidateOnStartup', '1', '默认值: 1 (启用)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.AllowPlayerCustomization', '允许玩家自定义', '1', '如果禁用，玩家无法改变任何插件的可见性', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.AllowCustomPositioning', '允许自定义位置', '1', '如果禁用，玩家无法移动插件窗口位置', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.DefaultSortOrder', '默认排序', '999', '新创建的插件会使用此排序值', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.ShowLoadingLog', 'ShowLoadingLog', '1', '默认值: 1 (显示)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.ShowCommandResult', '显示命令结果', '1', '默认值: 1 (显示)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.MaxCacheEntries', '最大缓存数', '10000', '当缓存超过此数值时，将清理最旧的条目', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.EnablePermissions', '启用权限', '1', '禁用后，所有插件对所有玩家可见，不考虑权限设置', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.AllowVIPPlugins', '允许VIP插件', '1', '此选项需要VIP系统的支持', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.DatabaseTimeout', '数据库超时', '5000', '默认值: 5000 (5秒)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.EnableHotReload', 'EnableHotReload', '1', '默认值: 1 (启用)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.ConfigCheckInterval', '配置检查间隔', '60', '系统会定期检查是否有新的插件配置需要加载', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.SendNotifications', '发送通知', '1', '默认值: 1 (启用)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.NotificationPosition', '通知位置', '0', '3 = 屏幕中央', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.AutoBackup', '自动备份', '1', '默认值: 1 (启用)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.BackupCount', '备份数量', '5', '默认值: 5', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.BackupPath', '备份路径', 'backup/plugin_manager', '默认值: backup/plugin_manager', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.Debug', '是否调试', '0', '启用后会输出更详细的日志信息', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.VerboseLogging', '详细日志', '0', '默认值: 0 (禁用)', 1),
(47, '插件管理器', 'mod_plugin_manager', 'PluginManager.MonitorPerformance', '监控性能', '0', '默认值: 0 (禁用)', 1),
(48, '宣传奖励', 'mod_promotion_reward', 'PromotionReward.Enable', '是否启用', '1', '是否启用', 1),
(48, '宣传奖励', 'mod_promotion_reward', 'PromotionReward.DebugLog', 'DebugLog', '0', 'DebugLog', 1),
(49, '宝箱系统', 'mod_treasure_box', 'TreasureBox.Enable', '是否启用', '1', '0 - 禁用', 1),
(49, '宝箱系统', 'mod_treasure_box', 'TreasureBox.Announce', '发送公告', '1', '0 - 禁用', 1),
(49, '宝箱系统', 'mod_treasure_box', 'TreasureBox.PopupWindow', 'PopupWindow', '1', '0 - 禁用', 1),
(49, '宝箱系统', 'mod_treasure_box', 'TreasureBox.Debug', '调试模式', '0', '设置为 1 输出宝箱调试日志', 1),
(50, '图鉴系统', 'mod_tujian_system', 'TujianSystem.Enable', '是否启用', '1', '默认: 1 (启用)', 1),
(50, '图鉴系统', 'mod_tujian_system', 'TujianSystem.Announce', '发送公告', '1', '发送公告', 1),
(51, '武魂系统', 'mod_wuhun_system', 'WuhunSystem.Enable', '是否启用', '1', '武魂系统', 1),
(51, '武魂系统', 'mod_wuhun_system', 'WuhunSystem.Debug', '是否调试', '0', '是否调试', 1),
(51, '武魂系统', 'mod_wuhun_system', 'WuhunSystem.AnnounceOnLogin', '登录公告', '1', '登录公告', 1),
(51, '武魂系统', 'mod_wuhun_system', 'WuhunSystem.AutoAttackSelectedTarget', 'AutoAttackSelectedTarget', '1', 'AutoAttackSelectedTarget', 1),
(51, '武魂系统', 'mod_wuhun_system', 'WuhunSystem.AutoAttackNearbyTarget', 'AutoAttackNearbyTarget', '1', 'AutoAttackNearbyTarget', 1),
(51, '武魂系统', 'mod_wuhun_system', 'WuhunSystem.AvatarSkillAI', 'AvatarSkillAI', '1', 'AvatarSkillAI', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.Enable', '是否启用', '1', '是否启用仙门系统', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.AnnounceOnLogin', '登录公告', '1', '登录时是否提示当前仙门信息', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.MaxLevel', '最高等级', '100', '仙门修为等级上限', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.SkillUnlockLevelStep', '每多少级获得 1 个门派技能解锁名额', '10', '每多少级获得 1 个门派技能解锁名额', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.TransferKeepLevelPct', '转投保留修为百分比', '50.000000', '转投门派时保留的修为百分比，最低保留 1 级', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.MaxActiveSkills', '门主最多可开放的门派技能数量', '10', '门主最多可开放的门派技能数量', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.MaxPersonalActiveSkills', '成员最多可选择的个人生效技能数量', '5', '成员最多可选择的个人生效技能数量', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.LeaderSettleCheckInterval', '每日门主结算检查间隔，单位秒', '60', '每日门主结算检查间隔，单位秒', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.EnableDailyLeaderSettle', '是否启用每日门主自动结算', '1', '是否启用每日门主自动结算', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.MaxDailyPublishes', '每日最多发布次数', '20', '每个角色每天最多发布仙门招募/公告次数', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.UpgradeContributionBase', '修为升级基础历史贡献', '100', '修为升级需要的基础历史贡献', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.UpgradeContributionPerLevel', '修为升级每级递增历史贡献', '10', '修为升级每级递增的历史贡献需求', 1),
(52, '仙门系统', 'mod_xianmen_system', 'XianmenSystem.DebugEffectiveSkillLog', '生效技能调试日志', '0', '一次属性重算会触发30-50次调用，默认必须关闭', 1),
(53, '战宠系统', 'mod_zhanchong', 'ZhanChong.Enable', '是否启用', '1', '0 - 禁用', 1),
(53, '战宠系统', 'mod_zhanchong', 'ZhanChong.Announce', '发送公告', '1', '0 - 禁用', 1),
(54, '自定义AI', 'mod-custom-ai', 'CustomAI.Enable', '是否启用', '1', '0 - 禁用', 1),
(54, '自定义AI', 'mod-custom-ai', 'CustomAI.Debug', '是否调试', '0', '1 - 启用', 1),
(54, '自定义AI', 'mod-custom-ai', 'CustomAI.UpdateInterval', '更新间隔', '1000', '默认: 1000', 1),
(55, '位置系统', 'mod-location-system', 'LocationSystem.Enable', '是否启用', '1', '是否启用定位坐标系统模块', 1),
(55, '位置系统', 'mod-location-system', 'LocationSystem.DebugMode', '调试模式', '0', '是否在聊天窗口显示调试信息', 1),
(55, '位置系统', 'mod-location-system', 'LocationSystem.ShowCoordinates', '是否在加载时显示坐标信息', '1', '是否在加载时显示坐标信息', 1),
(55, '位置系统', 'mod-location-system', 'LocationSystem.AllowPlayerCommands', '是否允许玩家使用定位命令（已禁用，只有GM可以使用）', '0', '是否允许玩家使用定位命令（已禁用，只有GM可以使用）', 1),
(55, '位置系统', 'mod-location-system', 'LocationSystem.MinGMLevel', '定位命令的最小GM等级 (0 = 玩家, 1 = 助手, 2 = 管理员, 3 = 超级管理员)', '1', '定位命令的最小GM等级 (0 = 玩家, 1 = 助手, 2 = 管理员, 3 = 超级管理员)', 1),
(55, '位置系统', 'mod-location-system', 'LocationSystem.CommandCooldown', '命令冷却', '60', '定位命令的冷却时间（秒）', 1),
(25, '地图属性', 'mod-map-attributes', 'Enable', '是否启用', '1', '启用地图属性系统', 1),
(25, '地图属性', 'mod-map-attributes', 'Debug', '是否调试', '0', '启用调试模式', 1),
(25, '地图属性', 'mod-map-attributes', 'Announce', '发送公告', '1', '启用地图公告', 1),
(25, '地图属性', 'mod-map-attributes', 'UpdateInterval', '更新间隔', '5000', '更新间隔（毫秒）', 1),
(56, '兑换码系统', 'mod-redemption-code', 'RedemptionCode.Enable', '是否启用', '1', '启用兑换码模块', 1),
(56, '兑换码系统', 'mod-redemption-code', 'RedemptionCode.InitDelay', 'InitDelay', '30', '默认: 30 (30秒)', 1),
(56, '兑换码系统', 'mod-redemption-code', 'RedemptionCode.Length', 'Length', '16', '默认: 16', 1),
(56, '兑换码系统', 'mod-redemption-code', 'RedemptionCode.Charset', 'Charset', 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', '默认: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', 1),
(56, '兑换码系统', 'mod-redemption-code', 'RedemptionCode.Announce', '发送公告', '1', '默认: 1 (启用)', 1),
(57, '自定义模块', 'my_custom', 'MyModule.Enable', '是否启用', '1', '是否启用', 1),
(58, '弹窗模板', 'PopupTemplate', 'PopupTemplate.Enable', '是否启用', '1', '默认: 1 (开启)', 1),
(58, '弹窗模板', 'PopupTemplate', 'PopupTemplate.Cooldown', 'Cooldown', '300', '默认: 300 (5分钟)', 1),
(58, '弹窗模板', 'PopupTemplate', 'PopupTemplate.PendingExpire', 'PendingExpire', '600', '默认: 600 (10分钟)', 1),
(58, '弹窗模板', 'PopupTemplate', 'PopupTemplate.Debug', '是否调试', '0', '默认: 0 (关闭)', 1),
(58, '弹窗模板', 'PopupTemplate', 'PopupTemplate.LoginPopupId', 'LoginPopupId', '1', '默认: 1', 1),
(59, '专业技能保留', 'ProfessionSkillRetention', 'ProfessionSkillRetention.Enable', '是否启用', '1', '设置为 0 禁用模块', 1),
(59, '专业技能保留', 'ProfessionSkillRetention', 'ProfessionSkillRetention.Debug', '是否调试', '0', '默认: 0 (禁用)', 1),
(60, '属性调整器', 'PropertyAdjuster', 'PropertyAdjuster.Enable', '是否启用', '1', '设置为 0 禁用', 1),
(60, '属性调整器', 'PropertyAdjuster', 'PropertyAdjuster.DebugMode', '调试模式', '0', '设置为 1 启用', 1),
(60, '属性调整器', 'PropertyAdjuster', 'PropertyAdjuster.LoadDelay', '加载延迟', '1', '服务器启动后多少秒加载模块', 1),
(61, '任务奖励属性', 'QuestRewardAttributes', 'QuestRewardAttributes.Enable', '是否启用', '1', '0 (禁用)', 1),
(61, '任务奖励属性', 'QuestRewardAttributes', 'QuestRewardAttributes.MaxQuestCount', 'MaxQuestCount', '0', '默认值: 0', 1),
(61, '任务奖励属性', 'QuestRewardAttributes', 'QuestRewardAttributes.ShowNotification', '0 (不显示)', '0', '0 (不显示)', 1),
(61, '任务奖励属性', 'QuestRewardAttributes', 'QuestRewardAttributes.ShowDetailedInfo', '1 (显示详细属性信息)', '0', '1 (显示详细属性信息)', 1),
(61, '任务奖励属性', 'QuestRewardAttributes', 'QuestRewardAttributes.DebugMode', '调试模式', '0', '1 (开启)', 1),
(62, '转生系统', 'reincarnation', 'Reincarnation.Enable', '是否启用', '1', '0 - 禁用', 1),
(62, '转生系统', 'reincarnation', 'Reincarnation.Debug', '是否调试', '0', '1 - 启用', 1),
(63, '需求模板', 'requirement_template', 'RequirementTemplate.Enable', '是否启用', '1', '0 - 禁用', 1),
(63, '需求模板', 'requirement_template', 'RequirementTemplate.AnnounceOnStartup', 'AnnounceOnStartup', '1', '0 - 禁用', 1),
(63, '需求模板', 'requirement_template', 'RequirementTemplate.ShowDetailedRequirements', 'ShowDetailedRequirements', '1', '0 - 禁用', 1),
(63, '需求模板', 'requirement_template', 'RequirementTemplate.InitDelay', 'InitDelay', '30', '默认: 30', 1),
(64, '奖励模板', 'reward-template', 'RewardTemplate.Enable', '是否启用', '1', '是否启用奖励模板系统', 1),
(64, '奖励模板', 'reward-template', 'RewardTemplate.CommandPermissionLevel', 'CommandPermissionLevel', '1', '3 - 控制台', 1),
(65, '符文系统', 'RuneSystem', 'RuneSystem.Enable', '是否启用', '1', '设置为 0 禁用', 1),
(65, '符文系统', 'RuneSystem', 'RuneSystem.ProcChanceFactor', 'ProcChanceFactor', '1.0', '默认: 1.0', 1),
(65, '符文系统', 'RuneSystem', 'RuneSystem.CooldownFactor', 'CooldownFactor', '1.0', '默认: 1.0', 1),
(65, '符文系统', 'RuneSystem', 'RuneSystem.DebugMode', '调试模式', '0', '默认: 0 (关闭)', 1),
(66, '生物模板', 'ShengwuMoban', 'ShengwuMoban.Enable', '是否启用', '1', '1 - 启用', 1),
(66, '生物模板', 'ShengwuMoban', 'ShengwuMoban.RandomTemplate.Enable', '是否启用', '1', '1 - 启用', 1),
(66, '生物模板', 'ShengwuMoban', 'ShengwuMoban.InstanceCooldown.Enable', '是否启用', '1', '1 - 启用', 1),
(66, '生物模板', 'ShengwuMoban', 'ShengwuMoban.Experience.Enable', '是否启用', '1', '1 - 启用', 1),
(66, '生物模板', 'ShengwuMoban', 'ShengwuMoban.DamageRanking.Enable', '是否启用', '1', '1 - 启用', 1),
(66, '生物模板', 'ShengwuMoban', 'ShengwuMoban.DebugMode', '调试模式', '0', '1 - 启用', 1),
(67, '技能控制', 'SkillControl', 'SkillControl.Enable', '是否启用', '1', '设置为0禁用', 1),
(67, '技能控制', 'SkillControl', 'SkillControl.Debug', '是否调试', '0', '设置为1启用', 1),
(67, '技能控制', 'SkillControl', 'Updates.AutoSetup', '设置为0禁用', '0', '设置为0禁用', 1),
(67, '技能控制', 'SkillControl', 'Updates.AllowedModules', '设置为空字符串禁用所有模块的自动更新', '', '设置为空字符串禁用所有模块的自动更新', 1),
(68, '技能大师', 'SkillMaster', 'SkillMaster.Enable', '是否启用', '1', '是否启用', 1),
(69, '天赋魂魄', 'talent_soul', 'TalentSoul.Enable', '是否启用', '1', '0 - 禁用', 1),
(69, '天赋魂魄', 'talent_soul', 'TalentSoul.Debug', '是否调试', '0', '1 - 启用', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.Enable', '是否启用', '1', '设置为0禁用模块', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.Debug', '是否调试', '0', '启用会显示更多日志信息', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.EnableInPublicAreas', 'EnableInPublicAreas', '1', '默认: 1 (允许)', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.EnableInBattlegrounds', 'EnableInBattlegrounds', '0', '默认: 0 (禁止)', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.EnableInArenas', 'EnableInArenas', '0', '默认: 0 (禁止)', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.EnableInCombat', 'EnableInCombat', '0', '默认: 0 (禁止)', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.EnableInInstances', 'EnableInInstances', '1', '默认: 1 (允许)', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.AutoCreateItem', '设置为0禁用物品自动创建', '1', '设置为0禁用物品自动创建', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.ItemEntry', '必须与数据库中的记录匹配', '50000', '必须与数据库中的记录匹配', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.AutoSpawnNPC', '设置为0禁用NPC自动生成', '1', '设置为0禁用NPC自动生成', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.NPCEntry', 'NPC模板ID', '100000', '必须与数据库中的记录匹配', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.NPCSpawnMap', 'NPC生成地图', '0', '默认: 0 (东部王国)', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.NPCSpawnX', 'NPC生成X坐标', '-8833.37', '默认值对应暴风城', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.NPCSpawnY', 'NPC生成Y坐标', '628.62', '传送NPC的生成位置 - Y坐标', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.NPCSpawnZ', 'NPC生成Z坐标', '94.00', '传送NPC的生成位置 - Z坐标', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.NPCSpawnO', 'NPC生成朝向', '1.06', '传送NPC的生成朝向', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.ItemCooldown', '物品冷却', '60', '默认: 60', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.TeleportCooldown', '传送冷却', '5', '默认: 5', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.MaxMenuItems', '最大菜单项', '16', '超过此数量会分页显示', 1),
(70, '传送系统', 'TeleportSystem', 'TeleportSystem.SaveLocation', '保存位置', '1', '可用于实现返回功能', 1),
(71, 'VIP系统', 'VipSystem', 'VipSystem.Enable', '是否启用', '1', '0 - 禁用', 1),
(71, 'VIP系统', 'VipSystem', 'VipSystem.AnnounceLogin', 'AnnounceLogin', '1', '0 - 禁用', 1),
(71, 'VIP系统', 'VipSystem', 'VipSystem.AutoApplyRates', 'AutoApplyRates', '1', '0 - 禁用', 1),
(71, 'VIP系统', 'VipSystem', 'VipSystem.DailyResetHour', '每日重置小时', '0', '默认: 0 - 午夜0点', 1),
(71, 'VIP系统', 'VipSystem', 'VipSystem.CommandCooldown', '命令冷却', '5', '默认: 5', 1),
(71, 'VIP系统', 'VipSystem', 'VipSystem.MaxVipLevel', '最高VIP等级', '1000', '默认: 5', 1),
(71, 'VIP系统', 'VipSystem', 'VipSystem.EnableDebug', '启用调试', '0', '1 - 启用', 1),
(72, '仙器系统', 'mod_xianmen_system', '仙器系统.启用', '是否启用', '1', '设置为 0 禁用仙器槽位系统', 1),
(72, '仙器系统', 'mod_xianmen_system', '仙器系统.调试模式', '调试模式', '0', '设置为 1 输出仙器调试日志', 1),
(72, '仙器系统', 'mod_xianmen_system', '仙器系统.属性倍率', '属性倍率', '1.000000', '仙器属性加成的全局倍率', 1),
(72, '仙器系统', 'mod_xianmen_system', '仙器系统.需要等级', '需要等级', '1', '使用仙器槽位的最低角色等级', 1),
(72, '仙器系统', 'mod_xianmen_system', '仙器系统.自动解锁', '自动解锁', '0', '设置为 1 时槽位自动解锁', 1)
ON DUPLICATE KEY UPDATE
  `模块ID` = VALUES(`模块ID`),
  `模块名称` = VALUES(`模块名称`),
  `模块标识` = VALUES(`模块标识`),
  `配置名称` = VALUES(`配置名称`),
  `配置值` = VALUES(`配置值`),
  `配置说明` = VALUES(`配置说明`),
  `启用状态` = VALUES(`启用状态`);

