#ifndef MODULE_ITEM_IDENTIFICATION_SYSTEM_LOADER_H
#define MODULE_ITEM_IDENTIFICATION_SYSTEM_LOADER_H

// 从模块加载脚本
void AddItemIdentificationSystemScripts();

#endif // MODULE_ITEM_IDENTIFICATION_SYSTEM_LOADER_H
