-- 神器任务链：spell_dbc 服务端草案数据
-- 说明：
-- 1. 本文件只写 world 库 spell_dbc 数据草案，不生成客户端 Spell.dbc，不打包客户端补丁。
-- 2. 80 个技能 ID：381001..381080；每阶 5 个击中特效。
-- 3. 技能 ID 只作为数据行主键。后续 C++ 增强逻辑必须读取 EffectBasePoints_1..3，不按技能 ID 判断。
-- 4. EffectBasePoints_1 = 主伤害比例，万分比；10000 = 100%，100 = 1%。
-- 5. EffectBasePoints_2 = 副效果参数；时空禁锢为定身秒数，噬魂回响为治疗万分比。
-- 6. EffectBasePoints_3 = 神器技能标记；9100101..9100105。

SET NAMES utf8mb4;

DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_levels`;
CREATE TEMPORARY TABLE `_tmp_artifact_spell_levels` (
  `rank_id` tinyint unsigned NOT NULL,
  PRIMARY KEY (`rank_id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `_tmp_artifact_spell_levels` (`rank_id`) VALUES
(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16);

DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_types`;
CREATE TEMPORARY TABLE `_tmp_artifact_spell_types` (
  `type_id` tinyint unsigned NOT NULL,
  `spell_name` varchar(64) NOT NULL,
  `marker` int NOT NULL,
  `damage_pct_base` int NOT NULL,
  `damage_pct_step` int NOT NULL,
  `misc_value` int NOT NULL,
  `school_mask` int unsigned NOT NULL,
  `spell_visual_id` int unsigned NOT NULL,
  `spell_icon_id` int unsigned NOT NULL,
  `description_template` varchar(255) NOT NULL,
  `aura_template` varchar(255) NOT NULL,
  PRIMARY KEY (`type_id`)
) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `_tmp_artifact_spell_types`
(`type_id`, `spell_name`, `marker`, `damage_pct_base`, `damage_pct_step`, `misc_value`, `school_mask`, `spell_visual_id`, `spell_icon_id`, `description_template`, `aura_template`) VALUES
(1, '天雷裁决', 9100101, 80,  20, 0,    8,  0, 136, '击中时有概率召下天雷，按神器战力百分比对目标造成自然伤害。',             '天雷轰击目标，造成自然伤害。'),
(2, '万剑归宗', 9100102, 60,  15, 0,    1,  0, 132, '击中时有概率释放万剑剑气，按神器战力百分比对目标造成神器伤害。',         '万剑归宗，剑气斩击目标。'),
(3, '时空禁锢', 9100103, 30,   8, 2,   64,  0, 135, '击中时有概率撕裂时空，按神器战力百分比对目标造成奥术伤害并定身2秒。',    '目标被时空裂隙禁锢。'),
(4, '噬魂回响', 9100104, 40,  10, 5000,32,  0, 136, '击中时有概率抽取目标灵魂，按神器战力百分比造成暗影伤害并治疗自身。',     '对目标造成暗影伤害并治疗自身。'),
(5, '终焉星爆', 9100105, 100, 25, 0,   64,  0, 135, '击中时有低概率引爆终焉星爆，按神器战力百分比对目标造成奥术爆发伤害。',   '终焉星爆爆发，造成奥术伤害。');

DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_defs`;
CREATE TEMPORARY TABLE `_tmp_artifact_spell_defs` AS
SELECT
  381001 + (l.`rank_id` - 1) * 5 + (t.`type_id` - 1) AS `spell_id`,
  l.`rank_id`,
  t.`type_id`,
  CONCAT(t.`spell_name`, '·第', l.`rank_id`, '阶') AS `spell_name`,
  t.`marker`,
  t.`damage_pct_base` + t.`damage_pct_step` * l.`rank_id` AS `damage_pct`,
  t.`misc_value`,
  t.`school_mask`,
  t.`spell_visual_id`,
  t.`spell_icon_id`,
  CONCAT(t.`description_template`, ' 当前比例：', ROUND((t.`damage_pct_base` + t.`damage_pct_step` * l.`rank_id`) / 100, 2), '%。') AS `spell_description`,
  t.`aura_template`
FROM `_tmp_artifact_spell_levels` l
JOIN `_tmp_artifact_spell_types` t
ORDER BY l.`rank_id`, t.`type_id`;

DELETE FROM `spell_dbc`
WHERE `ID` BETWEEN 381001 AND 381080;

DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_rows`;
CREATE TEMPORARY TABLE `_tmp_artifact_spell_rows` AS
SELECT
  d.`spell_id` AS `_artifact_spell_id`,
  d.`rank_id` AS `_artifact_rank_id`,
  d.`type_id` AS `_artifact_type_id`,
  d.`spell_name` AS `_artifact_spell_name`,
  d.`marker` AS `_artifact_marker`,
  d.`damage_pct` AS `_artifact_damage_pct`,
  d.`misc_value` AS `_artifact_misc_value`,
  d.`school_mask` AS `_artifact_school_mask`,
  d.`spell_visual_id` AS `_artifact_spell_visual_id`,
  d.`spell_icon_id` AS `_artifact_spell_icon_id`,
  d.`spell_description` AS `_artifact_spell_description`,
  d.`aura_template` AS `_artifact_aura_description`,
  s.*
FROM `_tmp_artifact_spell_defs` d
JOIN (
  SELECT COALESCE(
    (SELECT `ID` FROM `spell_dbc` WHERE `ID` = 35019 LIMIT 1),
    (SELECT `ID` FROM `spell_dbc` WHERE `ID` = 19 LIMIT 1)
  ) AS `source_id`
) src
JOIN `spell_dbc` s ON s.`ID` = src.`source_id`;

UPDATE `_tmp_artifact_spell_rows`
SET
  `ID` = `_artifact_spell_id`,
  `Category` = 0,
  `DispelType` = 0,
  `Mechanic` = 0,
  `Attributes` = 0,
  `AttributesEx` = 0,
  `AttributesEx2` = 0,
  `AttributesEx3` = 0,
  `AttributesEx4` = 0,
  `AttributesEx5` = 0,
  `AttributesEx6` = 0,
  `AttributesEx7` = 0,
  `Targets` = 0,
  `TargetCreatureType` = 0,
  `RequiresSpellFocus` = 0,
  `FacingCasterFlags` = 0,
  `CasterAuraState` = 0,
  `TargetAuraState` = 0,
  `ExcludeCasterAuraState` = 0,
  `ExcludeTargetAuraState` = 0,
  `CasterAuraSpell` = 0,
  `TargetAuraSpell` = 0,
  `ExcludeCasterAuraSpell` = 0,
  `ExcludeTargetAuraSpell` = 0,
  `CastingTimeIndex` = 1,
  `RecoveryTime` = 0,
  `CategoryRecoveryTime` = 0,
  `InterruptFlags` = 0,
  `AuraInterruptFlags` = 0,
  `ChannelInterruptFlags` = 0,
  `ProcTypeMask` = 0,
  `ProcChance` = 0,
  `ProcCharges` = 0,
  `MaxLevel` = 0,
  `BaseLevel` = 0,
  `SpellLevel` = 0,
  `DurationIndex` = 1,
  `PowerType` = 0,
  `ManaCost` = 0,
  `ManaCostPerLevel` = 0,
  `ManaPerSecond` = 0,
  `ManaPerSecondPerLevel` = 0,
  `RangeIndex` = 6,
  `Speed` = 0,
  `ModalNextSpell` = 0,
  `CumulativeAura` = 0,
  `Totem_1` = 0,
  `Totem_2` = 0,
  `Reagent_1` = 0,
  `Reagent_2` = 0,
  `Reagent_3` = 0,
  `Reagent_4` = 0,
  `Reagent_5` = 0,
  `Reagent_6` = 0,
  `Reagent_7` = 0,
  `Reagent_8` = 0,
  `ReagentCount_1` = 0,
  `ReagentCount_2` = 0,
  `ReagentCount_3` = 0,
  `ReagentCount_4` = 0,
  `ReagentCount_5` = 0,
  `ReagentCount_6` = 0,
  `ReagentCount_7` = 0,
  `ReagentCount_8` = 0,
  `EquippedItemClass` = -1,
  `EquippedItemSubclass` = 0,
  `EquippedItemInvTypes` = 0,
  `Effect_1` = 3,
  `Effect_2` = 3,
  `Effect_3` = 3,
  `EffectDieSides_1` = 0,
  `EffectDieSides_2` = 0,
  `EffectDieSides_3` = 0,
  `EffectRealPointsPerLevel_1` = 0,
  `EffectRealPointsPerLevel_2` = 0,
  `EffectRealPointsPerLevel_3` = 0,
  `EffectBasePoints_1` = `_artifact_damage_pct`,
  `EffectBasePoints_2` = `_artifact_misc_value`,
  `EffectBasePoints_3` = `_artifact_marker`,
  `EffectMechanic_1` = 0,
  `EffectMechanic_2` = 0,
  `EffectMechanic_3` = 0,
  `ImplicitTargetA_1` = 6,
  `ImplicitTargetA_2` = 6,
  `ImplicitTargetA_3` = 6,
  `ImplicitTargetB_1` = 0,
  `ImplicitTargetB_2` = 0,
  `ImplicitTargetB_3` = 0,
  `EffectRadiusIndex_1` = 0,
  `EffectRadiusIndex_2` = 0,
  `EffectRadiusIndex_3` = 0,
  `EffectAura_1` = 0,
  `EffectAura_2` = 0,
  `EffectAura_3` = 0,
  `EffectAuraPeriod_1` = 0,
  `EffectAuraPeriod_2` = 0,
  `EffectAuraPeriod_3` = 0,
  `EffectMultipleValue_1` = 0,
  `EffectMultipleValue_2` = 0,
  `EffectMultipleValue_3` = 0,
  `EffectChainTargets_1` = 0,
  `EffectChainTargets_2` = 0,
  `EffectChainTargets_3` = 0,
  `EffectItemType_1` = 0,
  `EffectItemType_2` = 0,
  `EffectItemType_3` = 0,
  `EffectMiscValue_1` = 0,
  `EffectMiscValue_2` = 0,
  `EffectMiscValue_3` = 0,
  `EffectMiscValueB_1` = 0,
  `EffectMiscValueB_2` = 0,
  `EffectMiscValueB_3` = 0,
  `EffectTriggerSpell_1` = 0,
  `EffectTriggerSpell_2` = 0,
  `EffectTriggerSpell_3` = 0,
  `EffectPointsPerCombo_1` = 0,
  `EffectPointsPerCombo_2` = 0,
  `EffectPointsPerCombo_3` = 0,
  `EffectSpellClassMaskA_1` = 0,
  `EffectSpellClassMaskA_2` = 0,
  `EffectSpellClassMaskA_3` = 0,
  `EffectSpellClassMaskB_1` = 0,
  `EffectSpellClassMaskB_2` = 0,
  `EffectSpellClassMaskB_3` = 0,
  `EffectSpellClassMaskC_1` = 0,
  `EffectSpellClassMaskC_2` = 0,
  `EffectSpellClassMaskC_3` = 0,
  `SpellVisualID_1` = `_artifact_spell_visual_id`,
  `SpellVisualID_2` = 0,
  `SpellIconID` = `_artifact_spell_icon_id`,
  `ActiveIconID` = `_artifact_spell_icon_id`,
  `SpellPriority` = 0,
  `Name_Lang_enUS` = `_artifact_spell_name`,
  `Name_Lang_enGB` = `_artifact_spell_name`,
  `Name_Lang_koKR` = `_artifact_spell_name`,
  `Name_Lang_frFR` = `_artifact_spell_name`,
  `Name_Lang_deDE` = `_artifact_spell_name`,
  `Name_Lang_enCN` = `_artifact_spell_name`,
  `Name_Lang_zhCN` = `_artifact_spell_name`,
  `Name_Lang_enTW` = `_artifact_spell_name`,
  `Name_Lang_zhTW` = `_artifact_spell_name`,
  `Name_Lang_esES` = `_artifact_spell_name`,
  `Name_Lang_esMX` = `_artifact_spell_name`,
  `Name_Lang_ruRU` = `_artifact_spell_name`,
  `Name_Lang_ptPT` = `_artifact_spell_name`,
  `Name_Lang_ptBR` = `_artifact_spell_name`,
  `Name_Lang_itIT` = `_artifact_spell_name`,
  `Name_Lang_Unk` = `_artifact_spell_name`,
  `Name_Lang_Mask` = 16712190,
  `NameSubtext_Lang_enUS` = '',
  `NameSubtext_Lang_enGB` = '',
  `NameSubtext_Lang_koKR` = '',
  `NameSubtext_Lang_frFR` = '',
  `NameSubtext_Lang_deDE` = '',
  `NameSubtext_Lang_enCN` = '',
  `NameSubtext_Lang_zhCN` = '',
  `NameSubtext_Lang_enTW` = '',
  `NameSubtext_Lang_zhTW` = '',
  `NameSubtext_Lang_esES` = '',
  `NameSubtext_Lang_esMX` = '',
  `NameSubtext_Lang_ruRU` = '',
  `NameSubtext_Lang_ptPT` = '',
  `NameSubtext_Lang_ptBR` = '',
  `NameSubtext_Lang_itIT` = '',
  `NameSubtext_Lang_Unk` = '',
  `NameSubtext_Lang_Mask` = 16712190,
  `Description_Lang_enUS` = `_artifact_spell_description`,
  `Description_Lang_enGB` = `_artifact_spell_description`,
  `Description_Lang_koKR` = `_artifact_spell_description`,
  `Description_Lang_frFR` = `_artifact_spell_description`,
  `Description_Lang_deDE` = `_artifact_spell_description`,
  `Description_Lang_enCN` = `_artifact_spell_description`,
  `Description_Lang_zhCN` = `_artifact_spell_description`,
  `Description_Lang_enTW` = `_artifact_spell_description`,
  `Description_Lang_zhTW` = `_artifact_spell_description`,
  `Description_Lang_esES` = `_artifact_spell_description`,
  `Description_Lang_esMX` = `_artifact_spell_description`,
  `Description_Lang_ruRU` = `_artifact_spell_description`,
  `Description_Lang_ptPT` = `_artifact_spell_description`,
  `Description_Lang_ptBR` = `_artifact_spell_description`,
  `Description_Lang_itIT` = `_artifact_spell_description`,
  `Description_Lang_Unk` = `_artifact_spell_description`,
  `Description_Lang_Mask` = 16712190,
  `AuraDescription_Lang_enUS` = `_artifact_aura_description`,
  `AuraDescription_Lang_enGB` = `_artifact_aura_description`,
  `AuraDescription_Lang_koKR` = `_artifact_aura_description`,
  `AuraDescription_Lang_frFR` = `_artifact_aura_description`,
  `AuraDescription_Lang_deDE` = `_artifact_aura_description`,
  `AuraDescription_Lang_enCN` = `_artifact_aura_description`,
  `AuraDescription_Lang_zhCN` = `_artifact_aura_description`,
  `AuraDescription_Lang_enTW` = `_artifact_aura_description`,
  `AuraDescription_Lang_zhTW` = `_artifact_aura_description`,
  `AuraDescription_Lang_esES` = `_artifact_aura_description`,
  `AuraDescription_Lang_esMX` = `_artifact_aura_description`,
  `AuraDescription_Lang_ruRU` = `_artifact_aura_description`,
  `AuraDescription_Lang_ptPT` = `_artifact_aura_description`,
  `AuraDescription_Lang_ptBR` = `_artifact_aura_description`,
  `AuraDescription_Lang_itIT` = `_artifact_aura_description`,
  `AuraDescription_Lang_Unk` = `_artifact_aura_description`,
  `AuraDescription_Lang_Mask` = 16712190,
  `ManaCostPct` = 0,
  `StartRecoveryCategory` = 0,
  `StartRecoveryTime` = 0,
  `MaxTargetLevel` = 0,
  `SpellClassSet` = 0,
  `SpellClassMask_1` = 0,
  `SpellClassMask_2` = 0,
  `SpellClassMask_3` = 0,
  `MaxTargets` = 1,
  `DefenseType` = 1,
  `PreventionType` = 0,
  `StanceBarOrder` = 0,
  `EffectChainAmplitude_1` = 0,
  `EffectChainAmplitude_2` = 0,
  `EffectChainAmplitude_3` = 0,
  `MinFactionID` = 0,
  `MinReputation` = 0,
  `RequiredAuraVision` = 0,
  `RequiredTotemCategoryID_1` = 0,
  `RequiredTotemCategoryID_2` = 0,
  `RequiredAreasID` = 0,
  `SchoolMask` = `_artifact_school_mask`,
  `RuneCostID` = 0,
  `SpellMissileID` = 0,
  `PowerDisplayID` = 0,
  `EffectBonusMultiplier_1` = 0,
  `EffectBonusMultiplier_2` = 0,
  `EffectBonusMultiplier_3` = 0,
  `SpellDescriptionVariableID` = 0,
  `SpellDifficultyID` = 0;

ALTER TABLE `_tmp_artifact_spell_rows`
  DROP COLUMN `_artifact_spell_id`,
  DROP COLUMN `_artifact_rank_id`,
  DROP COLUMN `_artifact_type_id`,
  DROP COLUMN `_artifact_spell_name`,
  DROP COLUMN `_artifact_marker`,
  DROP COLUMN `_artifact_damage_pct`,
  DROP COLUMN `_artifact_misc_value`,
  DROP COLUMN `_artifact_school_mask`,
  DROP COLUMN `_artifact_spell_visual_id`,
  DROP COLUMN `_artifact_spell_icon_id`,
  DROP COLUMN `_artifact_spell_description`,
  DROP COLUMN `_artifact_aura_description`;

REPLACE INTO `spell_dbc`
SELECT *
FROM `_tmp_artifact_spell_rows`;

DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_rows`;
DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_defs`;
DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_types`;
DROP TEMPORARY TABLE IF EXISTS `_tmp_artifact_spell_levels`;
