#ifndef ITEM_PURCHASE_LIMIT_H
#define ITEM_PURCHASE_LIMIT_H

enum ItemPurchaseLimitStatements
{
    WORLD_SEL_ITEM_PURCHASE_LIMIT_CONFIG,
    CHAR_SEL_ITEM_PURCHASE_DAILY_ACCOUNT,
    CHAR_SEL_ITEM_PURCHASE_DAILY_CHARACTER,
    CHAR_SEL_ITEM_PURCHASE_DAILY_SERVER,
    CHAR_SEL_ITEM_PURCHASE_PERMANENT_ACCOUNT,
    CHAR_SEL_ITEM_PURCHASE_PERMANENT_CHARACTER,
    CHAR_SEL_ITEM_PURCHASE_PERMANENT_SERVER,
    CHAR_INS_ITEM_PURCHASE_RECORD,
    MAX_ITEM_PURCHASE_LIMIT_STATEMENTS
};

// 添加脚本加载函数的声明
void AddSC_ItemPurchaseLimitScripts();

#endif // ITEM_PURCHASE_LIMIT_H 