SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `_穿戴等级权限` (
  `玩家GUID` INT UNSIGNED NOT NULL COMMENT 'characters.guid',
  `穿戴等级` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '玩家已解锁的最高穿戴等级；默认1级',
  `更新时间` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`玩家GUID`),
  KEY `idx_穿戴等级权限_穿戴等级` (`穿戴等级`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='玩家穿戴等级权限';
